#' Synthetic RDD dataset for wsga examples
#'
#' A simulated dataset with 2,000 observations designed to illustrate
#' weighted subgroup analysis in a regression discontinuity setting. The
#' running variable is centered at zero (cutoff = 0). The continuous moderator
#' `m` is imbalanced across subgroups near the cutoff, making IPW reweighting
#' non-trivial. True sharp RD effects are 2 for subgroup 0 and 4 for subgroup 1
#' (true difference = 2).
#'
#' @format A data frame with 2,000 rows and 6 columns:
#' \describe{
#'   \item{x}{Running variable, drawn from Uniform(-1, 1). Cutoff at 0.}
#'   \item{sgroup}{Binary subgroup indicator (0 or 1).}
#'   \item{m}{Continuous moderator. Mean differs across subgroups near cutoff.}
#'   \item{Z}{Sharp treatment assignment: `1(x > 0)`.}
#'   \item{D}{Fuzzy treatment receipt (~80% compliance above cutoff, ~10% below).}
#'   \item{y}{Outcome variable.}
#' }
#' @source Generated by `inst/generate_synth.R` with `set.seed(42)`.
#' @docType data
#' @usage data(rddsga_synth)
#' @keywords datasets
"rddsga_synth"

#' Synthetic balanced-panel DiD dataset for wsga examples
#'
#' A simulated balanced two-period panel with 500 units (1,000 rows) designed
#' to illustrate weighted subgroup analysis in a sharp difference-in-differences
#' setting. The binary subgroup indicator `sgroup` is constant within unit, and
#' the continuous moderator `m` has different means across subgroups (creating
#' the imbalance that IPW corrects). The binary treatment `D` is also constant
#' within unit and is independent of `sgroup`. True per-subgroup treatment
#' effects on the post-period outcome are `tau_0 = 1` for `sgroup = 0` and
#' `tau_1 = 3` for `sgroup = 1` (true difference = 2).
#'
#' @format A data frame with 1,000 rows and 6 columns:
#' \describe{
#'   \item{unit}{Integer unit identifier (1..500). Each unit appears in 2 rows.}
#'   \item{time}{Integer period indicator: `0` = pre, `1` = post.}
#'   \item{sgroup}{Binary subgroup indicator (0 or 1), constant within unit.}
#'   \item{m}{Continuous moderator, constant within unit. Mean differs across
#'     subgroups.}
#'   \item{D}{Binary treatment indicator, constant within unit, independent of
#'     `sgroup`.}
#'   \item{y}{Outcome variable.}
#' }
#' @source Generated by `inst/generate_did_synth.R` with `set.seed(7)`.
#' @docType data
#' @usage data(wsga_did_synth)
#' @keywords datasets
"wsga_did_synth"
