#' Synthetic dataset for rddsga examples
#'
#' A simulated dataset with 2,000 observations designed to illustrate
#' weighted subgroup analysis in a regression discontinuity setting. The
#' running variable is centered at zero (cutoff = 0). The continuous moderator
#' `m` is imbalanced across subgroups near the cutoff, making IPW reweighting
#' non-trivial. True sharp RD effects are 2 for subgroup 0 and 4 for subgroup 1
#' (true difference = 2).
#'
#' @format A data frame with 2,000 rows and 6 columns:
#' \describe{
#'   \item{x}{Running variable, drawn from Uniform(-1, 1). Cutoff at 0.}
#'   \item{sgroup}{Binary subgroup indicator (0 or 1).}
#'   \item{m}{Continuous moderator. Mean differs across subgroups near cutoff.}
#'   \item{Z}{Sharp treatment assignment: `1(x > 0)`.}
#'   \item{D}{Fuzzy treatment receipt (~80% compliance above cutoff, ~10% below).}
#'   \item{y}{Outcome variable.}
#' }
#' @source Generated by `inst/generate_synth.R` with `set.seed(42)`.
#' @docType data
#' @usage data(rddsga_synth)
#' @keywords datasets
"rddsga_synth"
